version: "3"
 
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  app:
    build:
      context: ./translator
      dockerfile: Dockerfile
    volumes:
      - ./translator:/app
    ports:
      - "3000:3000"