version: "3.9"
 
services:
  mariadb:
    container_name: translator_mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    restart: always
    healthcheck:
      test: exit 0
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
  app:
    container_name: translator_app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3001:3001"
    depends_on: 
      mariadb:
        condition: service_healthy
    secrets:
      - okamotolab
      - api_key
      - db_settings
    expose:
      - 3001
  nginx:
    container_name: translator_nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
secrets:
  db_root_password: 
    file: ./secrets/db_root_password
  api_key:
    file: ./secrets/api_key
  okamotolab:
    file: ./secrets/okamotolab
  db_settings:
    file: ./secrets/db_settings
