version: "3.9"
 
services:
  nginx:
    container_name: translator_nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    container_name: translator_app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3001:3001"
    depends_on:
      - database
    secrets:
      - okamotolab
      - deepl_api_key
      - db_settings
    expose:
      - 3001
  database:
    container_name: translator_db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./database:/database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    restart: always
    secrets:
      - db_root_password
secrets:
  db_root_password: 
    file: ./secrets/db_root_password
  deepl_api_key:
    file: ./secrets/api_key
  okamotolab:
    file: ./secrets/okamotolab
  db_settings:
    file: ./secrets/db_settings