version: "3"
 
services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3001:3001"
    secrets:
      - members
      - api_key
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - type: volume

      # -./database:/database
# secrets:
#   menbers: 
#     file: menbers.json
#   api_key: 
#     file: api_key.txt